"""Export the landmark classifier for the dependency-free Pages runtime."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import torch

from asl_recognition.constants import CLASS_NAMES
from asl_recognition.landmark_model import FEATURE_CONTRACT, load_landmark_checkpoint
from asl_recognition.landmarks import (
    FEATURE_DIMENSION,
    FINGERTIPS,
    HAND_LANDMARKER_TASK_URL,
    INDEX_MCP,
    MIDDLE_MCP,
    PINKY_MCP,
    RING_MCP,
    WRIST,
)

ROOT = Path(__file__).resolve().parents[1]
CHECKPOINT = ROOT / "models" / "asl_landmark_mlp_seed42.pt"
ASSET_DIR = ROOT / "site" / "assets"
MANIFEST_PATH = ASSET_DIR / "landmark-model-manifest.json"
WEIGHTS_PATH = ASSET_DIR / "asl-landmark-mlp-v1.f32"
PARITY_PATH = ROOT / "tools" / "landmark_model_parity.json"


def main() -> None:
    model, metadata = load_landmark_checkpoint(CHECKPOINT, map_location="cpu")
    model.eval()

    tensors: list[dict[str, object]] = []
    chunks: list[bytes] = []
    offset = 0
    for name, value in model.state_dict().items():
        if name.endswith("num_batches_tracked"):
            continue
        array = value.detach().cpu().contiguous().numpy().astype("<f4", copy=False)
        tensors.append(
            {"name": name, "shape": list(array.shape), "offset": offset, "length": int(array.size)}
        )
        chunks.append(array.tobytes(order="C"))
        offset += int(array.size)

    ASSET_DIR.mkdir(parents=True, exist_ok=True)
    weights = b"".join(chunks)
    WEIGHTS_PATH.write_bytes(weights)

    manifest = {
        "format": "asl-landmark-mlp-v1",
        "source_checkpoint_sha256": hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest(),
        "architecture": metadata["architecture"],
        "feature_contract": FEATURE_CONTRACT,
        "feature_dimension": FEATURE_DIMENSION,
        "class_names": list(CLASS_NAMES),
        "hand_landmarker_task_url": HAND_LANDMARKER_TASK_URL,
        # The JS normaliser must agree with the Python one exactly, so the indices
        # it depends on travel with the weights rather than being duplicated by
        # hand in two languages.
        "landmark_indices": {
            "wrist": WRIST,
            "index_mcp": INDEX_MCP,
            "middle_mcp": MIDDLE_MCP,
            "ring_mcp": RING_MCP,
            "pinky_mcp": PINKY_MCP,
            "fingertips": list(FINGERTIPS),
        },
        "float_count": offset,
        "weight_sha256": hashlib.sha256(weights).hexdigest(),
        "tensors": tensors,
    }
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    # Deterministic parity vector, generated by the same LCG the CNN parity uses
    # so the browser can reproduce it without shipping a fixture file.
    state = 42
    values: list[float] = []
    for _ in range(FEATURE_DIMENSION):
        state = (state * 1_664_525 + 1_013_904_223) & 0xFFFFFFFF
        values.append((state / 4_294_967_296) * 2.0 - 1.0)
    with torch.inference_mode():
        expected = torch.softmax(
            model(torch.tensor(values, dtype=torch.float32).reshape(1, FEATURE_DIMENSION)), dim=1
        )[0].tolist()
    PARITY_PATH.write_text(
        json.dumps({"seed": 42, "features": values, "expected": expected}, indent=2) + "\n",
        encoding="utf-8",
    )

    print(f"wrote {WEIGHTS_PATH.relative_to(ROOT)} ({len(weights):,} bytes)")
    print(f"wrote {MANIFEST_PATH.relative_to(ROOT)}")
    print(f"wrote {PARITY_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
